name: Check, Build and Test

on: [push, pull_request]

jobs:
  ci:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        rust-toolchain: [nightly]
        targets: [riscv64gc-unknown-none-elf]
    steps:
    - uses: actions/checkout@v4
    - uses: taiki-e/install-action@v2
      with:
        tool: cargo-hack,cargo-binutils
    - uses: dtolnay/rust-toolchain@nightly
      with:
        toolchain: ${{ matrix.rust-toolchain }}
        components: rust-src, clippy, rustfmt
        targets: ${{ matrix.targets }}
    - name: Check rust version
      run: rustc --version --verbose
    - name: Check code format
      run: cargo fmt --all -- --check
    - name: Clippy
      run: cargo hack clippy --target ${{ matrix.targets }} --each-feature
    - name: Build
      run: cargo hack build --target ${{ matrix.targets }} --each-feature

    # FIXME: cp: cannot create regular file '../../../tftpboot/': Not a directory
    - name: Run Example
      run: cd example && make all
